"""empty message

Revision ID: 0a23ec766e91
Revises: f5e5f4362034
Create Date: 2019-03-03 21:15:28.426690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a23ec766e91'
down_revision = 'f5e5f4362034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'term')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('term', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
