"""empty message

Revision ID: 510d23bed0de
Revises: 4925f86de721
Create Date: 2019-04-25 20:46:13.979439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '510d23bed0de'
down_revision = '4925f86de721'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timetable', sa.Column('duration', sa.Float(), nullable=True))
    op.add_column('timetable', sa.Column('professor', sa.String(), nullable=True))
    op.add_column('timetable', sa.Column('studentgroup', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timetable', 'studentgroup')
    op.drop_column('timetable', 'professor')
    op.drop_column('timetable', 'duration')
    # ### end Alembic commands ###
