"""empty message

Revision ID: 536f485b9478
Revises: 0eb683b7f6ba
Create Date: 2019-03-18 16:40:09.594656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '536f485b9478'
down_revision = '0eb683b7f6ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('userGroup', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'userGroup')
    # ### end Alembic commands ###
