"""empty message

Revision ID: 5afb43ce11e5
Revises: f5d1c8266f84
Create Date: 2019-03-03 21:37:27.561996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5afb43ce11e5'
down_revision = 'f5d1c8266f84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'term')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('term', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
