"""empty message

Revision ID: 78de5fb5821a
Revises: d2c3e0d01c86
Create Date: 2019-04-08 14:49:27.661609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78de5fb5821a'
down_revision = 'd2c3e0d01c86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pillar', sa.String(), nullable=True))
    op.add_column('users', sa.Column('student_group', sa.String(), nullable=True))
    op.add_column('users', sa.Column('student_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('term', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'term')
    op.drop_column('users', 'student_id')
    op.drop_column('users', 'student_group')
    op.drop_column('users', 'pillar')
    # ### end Alembic commands ###
