"""empty message

Revision ID: 816172963b30
Revises: 78de5fb5821a
Create Date: 2019-04-12 17:01:48.200100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '816172963b30'
down_revision = '78de5fb5821a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('cohortnum', sa.Integer(), nullable=True))
    op.add_column('subjects', sa.Column('components', sa.String(), nullable=True))
    op.add_column('subjects', sa.Column('pillar', sa.Integer(), nullable=True))
    op.add_column('subjects', sa.Column('sessionnum', sa.Integer(), nullable=True))
    op.add_column('subjects', sa.Column('totalenrollment', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'totalenrollment')
    op.drop_column('subjects', 'sessionnum')
    op.drop_column('subjects', 'pillar')
    op.drop_column('subjects', 'components')
    op.drop_column('subjects', 'cohortnum')
    # ### end Alembic commands ###
