"""empty message

Revision ID: 98df9e8707c8
Revises: 6f8c16191ed5
Create Date: 2019-03-03 20:06:45.930430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98df9e8707c8'
down_revision = '6f8c16191ed5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
