"""empty message

Revision ID: d2c3e0d01c86
Revises: 536f485b9478
Create Date: 2019-03-24 12:26:39.205299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2c3e0d01c86'
down_revision = '536f485b9478'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_group', sa.String(length=128), nullable=True))
    op.drop_column('users', 'userGroup')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('userGroup', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('users', 'user_group')
    # ### end Alembic commands ###
