"""empty message

Revision ID: ebeedfebf42c
Revises: 816172963b30
Create Date: 2019-04-12 17:28:20.491184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebeedfebf42c'
down_revision = '816172963b30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('coursetable', sa.String(), nullable=True))
    op.add_column('users', sa.Column('professor_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'professor_id')
    op.drop_column('users', 'coursetable')
    # ### end Alembic commands ###
