"""empty message

Revision ID: f5e5f4362034
Revises: 98df9e8707c8
Create Date: 2019-03-03 21:09:04.112019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5e5f4362034'
down_revision = '98df9e8707c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('term', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'term')
    # ### end Alembic commands ###
